### ISSUE TITLE
Cannot require image in the generate process 

### ISSUE THREAD

**Issue by mauricemojito** [d1urno/nuxt-image-extractor#2]
My problem is this:
1) I require the image `~/dist/_images/storage-images-xxxx-yyyy-zzzzz.jpg)`
2) The first time I run nuxt generate I got: `Module not found: Error: Can't resolve` + image name and path
3) I comment the require statement out and run the process again: `nuxt generate`
4) This time all images are extracted, because there're in the nuxt dist folder
5) When I delete the dist folder or the image isn't downloaded yet I got the same error: `Module not found: Error: Can't resolve` + image name and path
Is there any workaround by this, I mean it's logical that It cannot require an image if it isn't set yet. Anyways, it's a nice module. Thank you!

**Comment by d1urno** [comment]
This module wasn't meant to do that, it only process images that are pointing to an external API. `require` method is for loading locally stored images, if that's what you need, use `assets` folder and `require` them from there. 
By the way `dist` folder is an output folder, your project shouldn't process any files inside it 🤔.

**Comment by mauricemojito** [comment]
The idea behind this was to convert jpeg images to webp, but the image optimization package said that the next version of nuxt will have a method to externally require images and process them. I understand that this package allows only to display images that are downloaded, but would be really great if it'll be possible to process external images.
