### ISSUE TITLE
"page.html.matchAll is not a function" error on generate

### ISSUE THREAD

**Issue by thomas-ricci** [d1urno/nuxt-image-extractor#3]
Hi. Upon running `generate` the process fails citing this error. I'm running version `1.1.3` with nuxt version `2.14.0`. Let me know if I can provide any extra information!

```
...
ℹ Generating output directory: dist/                                   08:52:29
ℹ Generating pages                                                     08:52:30

 FATAL  page.html.matchAll is not a function                           08:52:30

  at process (node_modules/nuxt-image-extractor/lib/module.js:48:31)
  at Extract.nuxt.hook (node_modules/nuxt-image-extractor/lib/module.js:26:18)
  at o (node_modules/hable/dist/hable.js:1:1052)
  at o.then.o (node_modules/hable/dist/hable.js:1:270)
  at process._tickCallback (internal/process/next_tick.js:68:7)


   ╭─────────────────────────────────────────────────────╮
   │                                                     │
   │   ✖ Nuxt Fatal Error                                │
   │                                                     │
   │   TypeError: page.html.matchAll is not a function   │
   │                                                     │
   ╰─────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tr-web@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tr-web@1.0.0 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomas/.npm/_logs/2020-10-19T21_52_31_009Z-debug.log
```

**Comment by d1urno** [comment]
Can you please provide a temporary repository so I can reproduce this error?

**Comment by thomas-ricci** [comment]
Hey @d1urno I've just added you as a collaborator to a test repo. Apologies I didn't have too much time to go into detail.

I'm not sure if it makes too much of a difference but I'm using [Dato CMS](https://www.datocms.com/) for my content management. I've configured your package correctly to my knowledge. This is a tiny part of my project. There are only two possible routes here with what I've got in the CMS (as specified at the top of `nuxt.config.js`:
1. `/projects/adrift`
2. `/projects/wellbeing-of-sydney`

Each is just a `<p>` element of the title and a small image.

If I disable your module it successfully generates the static files and the `<img>` `src` attribute has a value pointing to the external CMS server. If I enable the module I get the _page.html.matchAll is not a function_ error.

**Comment by d1urno** [comment]
I've tested your repository and everything went just fine, just enabled `target: 'static'` in nuxt config file before executing `npm run generate`.

I believe your node version could be outdated...

> #String.matchAll is supported in Node.js from version 12.0.0

Anyways, I will clean those deprecation messages, and some parsing errors happening when `target: 'static'` is not specified.

**Comment by thomas-ricci** [comment]
Yes that was it, thanks so much. I was still on v10.*. Been having issues with NVM on my machine. Can confirm it's working like a charm now. This module is awesome.
