### ISSUE TITLE
Download images Contentful

### ISSUE THREAD

**Issue by pellens** [d1urno/nuxt-image-extractor#8]
Hi,

I'm using your plugin, but it doesn't seem to do anything...
- No errors (build, generate, ... works)
- No image downloaded
- No templates adjusted with the `/_images` folder...

I'm trying to download the images from Contenful CMS.
Any knowledge? Thanks!

**Comment by d1urno** [comment]
Have you included the base CMS address in the configuration?
I can't tell what's going on without having information. Can you upload a simple repository with your setup so I can reproduce the issue?

**Comment by pellens** [comment]
An example url of an image is like such:

http://images.ctfassets.net/jsc9w1b7a9ly/3g7TKz3svRQ9o1VSrCLs2P/a9f1551f98c9756a6465041f365fe6b1/hero.jpeg?fit=fill&w=570&h=430

It's a Contenful Assets url... Tries some configurations, but I guess I'm stuck...
Is this info helpful?

**Update:**
Conteful is serving the images as such:
//images.ctfassets.net/jsc9w1b7a9ly/3g7TKz3svRQ9o1VSrCLs2P/a9f1551f98c9756a6465041f365fe6b1/hero.jpeg?fit=fill&w=570&h=430

So putting "http:" before the images, does indeed download the images. But it is still not replacing it in de dist-files... Any experience with that?

**Comment by d1urno** [comment]
I've tested that image with this config and it's working fine.

on nuxt.config.js
```
target: 'static',
modules: [
    [
      'nuxt-image-extractor',
      { baseUrl: 'http://images.ctfassets.net' }
    ]
],
```
Then you run the following commands `nuxt build` `nuxt generate` and `nuxt start` to check the output live server.
This generates a `dist` folder, wich contains the `_images` folder, and then serves it (on `localhost:3000` by default).
